app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

admin_change_password:
    path: /admin/change-password
    controller: App\Controller\Admin\DashboardController::changePassword

app_forgot_password_request:
    path: /forgot-password
    controller: App\Controller\Security\ForgotPasswordController::request

app_reset_password:
    path: /reset-password/{token}
    controller: App\Controller\Security\ResetPasswordController::reset

admin_change_email:
    path: /admin/change-email
    controller: App\Controller\Admin\DashboardController::changeEmail

admin_confirm_email:
    path: /admin/confirm-email/{token}
    controller: App\Controller\Admin\DashboardController::confirmEmail

sitemap:
    path: /sitemap.xml
    controller: App\Controller\SitemapController::index