# config/services.yaml

# Paramètres globaux de l'application
parameters: {}

# Configuration des services
services:
    # Configuration par défaut pour tous les services déclarés dans ce fichier
    _defaults:
        autowire: true      # Injection automatique des dépendances
        autoconfigure: true # Configuration automatique pour les commandes, subscribers, etc.
        public: false       # Tous les services sont privés par défaut

    # Déclaration des services de l'application : src/ est analysé automatiquement
    App\:
        resource: '../src/'
        # Exclure les répertoires spécifiques si besoin
        # exclude: '../src/{DependencyInjection,Entity,Migrations,Tests}'

    # Déclarer explicitement tes controllers comme publics pour Symfony 8
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        public: true

    App\Controller\Security\ForgotPasswordController:
        public: true
        tags: ['controller.service_arguments']